### ISSUE TITLE
$$PackageHelper classes/generated methods

### ISSUE THREAD

**Issue by liangricha** [johncarl81/parceler#150]
Hi! I noticed a bunch of generated `<CLASS_NAME>$$PackageHelper` methods and also a bunch of generated accessors for some classes (but not all) that I annotated with `@Parcel`. What causes Parceler to generate these classes/methods, and is there any way to prevent this behavior?

Thanks!

**Comment by johncarl81** [comment]
Parceler will generate these package helpers in order to access protected fields or methods.  It shouldn't be generating package helpers for package private modifiers as the generated Parcelable accesses your class within the same package.  Use public or package private fields / methods to avoid these classes being generated.

**Comment by liangricha** [comment]
Gotcha - thanks for the quick answer!
