### ISSUE TITLE
Make original class implement Parcelable directly

### ISSUE THREAD

**Issue by mikaelstaldal** [johncarl81/parceler#166]
It would be nice if Parceler could transform the original class to implement `Parcelable` directly, and thereby alleviating the need for runtime wrapping and the `org.parceler.Parcels` class.

[Lombok](https://github.com/rzwitserloot/lombok) does this kind of transformation of classes.

**Comment by tom91136** [comment]
With what I know, implementing this will require significant effort. 

Here are some possible solutions, point 2 outlines the effort required for this to work.

1. We can eliminate the `Parcels.wrap` call and make your classes implement Parcelable, but then you would have to implement all the methods too (what [ParcelablePlease](https://github.com/sockeqwe/ParcelablePlease) is doing). 

2. We can modify the bytecode of the annotated class so that it implements Parcelable, but then we have to create a plugin for our toolings too(otherwise your favourite IDE will mark it as an error), lombok goes with this approach. I believe too many things can go wrong and does not justify the small the convenience of eliminating `Parcels.wrap`.

3. We cannot transform classes in the Android API so we can't make `Bundle`'s API accept `Object`s. But we can make an utility class that accepts `Object`s and then you can store it in your bundle. That utility class will call `Parcels.wrap` for you for all your objects. This only solves the `wrap` side, 

So far, we can handle the most common use case of parcelable: persist states across configuration change. This has been done in some libraries already like [Akatsuki](https://github.com/tom91136/Akatsuki) and  [Icepick](https://github.com/frankiesardo/icepick).

But in the end, it's up to @johncarl81

**Comment by mikaelstaldal** [comment]
It is option 2 I am after, neither option 1 nor option 3 are sufficient.

Yes, we would need a plugin for IntelliJ IDEA / AndroidStudio as well (there is a [such plugin for Lombok](https://github.com/mplushnikov/lombok-intellij-plugin)).

**Comment by johncarl81** [comment]
FYI, Lombok leverages a [trick in the java compiler to do this](http://notatube.blogspot.com/2010/11/project-lombok-trick-explained.html).  AST transformations are not official supported by the Java Annotation Processor spec.

Is the only want to remove the Parcels utility class wrap / unwrap call?  You could call the generated `Parcelable` constructor / `getParcel()` method directly then:

```java
ExampleParcel exampleParcel = new ExampleParcel();
ExampleParcel$$Parcelable parcelable = new ExampleParcel$$Parcelable(exampleParcel);
ExampleParcel unwrapped = parcelable.getParcel();
```

But, I doubt that is what you're after.  What are you really after here?

**Comment by tom91136** [comment]
I believe  @mikaelstaldal wants to Parceler to be transparent(invisible),  i.e  does not require wrapping

**Comment by johncarl81** [comment]
Not sure if there is a silver bullet here... each library has its own features and drawbacks, Parceler's drawback is your beans need to be wrapped.  We might be able to support an approach like ParcelablePlease does, but that also requires a fair amount of boilerplate to be able to handle both making your class extend Parcelable and writeToParcel / createFromParcel.

As always I'm open to new ideas though :smiley:

**Comment by mikaelstaldal** [comment]
The [article about Lombok's trick](http://notatube.blogspot.se/2010/11/project-lombok-trick-explained.html) is from 2010. Since then Java 7 and Java 8 has been released. Does that change anything?

**Comment by mikaelstaldal** [comment]
Yes, I want Parceler to be transparent (similar to Lombok).

**Comment by johncarl81** [comment]
Knowing JSR 269, I doubt this technique has changed, but it's possible they are doing something else.
