### ISSUE TITLE
Error:Parceler: Unable to find read/write generator for type com.activeandroid.TableInfo for com.activeandroid.Model.mTableInfo

### ISSUE THREAD

**Issue by levisaturnino** [johncarl81/parceler#216]
I am wanting to use Parceler with ActiveAndroid, when I put the two together Android gives me this error: 
`Error: Parceler: Unable to find read / write generator for type com.activeandroid.TableInfo is com.activeandroid.Model.mTableInfo in the City class.`
How do I solve?

```java
@Parcel
@Table(name = "Cidade")
public class Cidade  extends Model{

    @Column(name = "id")
    public Long id;
    @Column(name = "nome")
    public String nome;
    @Column(name = "imagem")
    public String imagem;

    @Override
    public String toString() {
        return  nome;
    }
}
```

**Comment by johncarl81** [comment]
Since your class extends a base class (`Model`) Parceler is attempting to analyze and generate code to marshal fields in that case class.  To avoid this you'll need to define explicitly what types Parceler should analyze.  This should work for your case:

```java
@Parcel(analyze = Cidade.class)
@Table(name = "Cidade")
public class Cidade extends Model{
    @Column(name = "id")
    public Long id;
    @Column(name = "nome")
    public String nome;
    @Column(name = "imagem")
    public String imagem;

    @Override
    public String toString() {
        return  nome;
    }
}
```
Here's a link to the relavent docs:  http://parceler.org/#skipping_analysis
