### ISSUE TITLE
Does parceler work well with databinding?

### ISSUE THREAD

**Issue by jayjaykim** [johncarl81/parceler#337]
Hello.
Recently, I had a chance to make some classes as Parcelable. But while building the application, databinding proxy classes cannot be built at all when using @Parcel annotation on some POJO classes. Have you ever tested parceler works well with databinding?

**Comment by johncarl81** [comment]
I've worked with it a little.  Give it a try and let us know if it could be better?

**Comment by CapnSpellcheck** [comment]
Can you give some code demonstration? I use both libraries. I use `@Parcel` on a few of my models, and looking through them, 2 are also BaseObservable. In some others, I use ObservableFields. But I'm not sure what are data binding proxy classes, since I don't think you interface with them at all. (I think the autogenerated bindings are referred to as bindings or binding classes.)
