### ISSUE TITLE
Jackson Mixin style annotations

### ISSUE THREAD

**Issue by tom91136** [johncarl81/parceler#58]
Sometimes, we have a external library were `@ParcelClass` doesn't work very well.
Is it possible to introduce something like Mixins in the Jackson JSON library? 

Here are the docs:
http://wiki.fasterxml.com/JacksonMixInAnnotations

**Comment by johncarl81** [comment]
@tom91136, I haven't deployed it yet, but the beginnings of this is available on the referenced PR if you want to play with an early preview.

**Comment by tom91136** [comment]
Sorry I was having exams in uni, I'm back now. I was testing out 0.2.16-SNAPSHOT and found that it's a bit different from the PR, is there an example on how I would use `@Parcel annotation()`?

**Comment by johncarl81** [comment]
@tom91136 This is definitely a WIP.  You can find this progress under #62 if you want to play with it.  I'd greatly appreciate your feedback.

**Comment by johncarl81** [comment]
I've been thinking about this feature for a couple months now, and I've come to the conclusion that it's largely unnecessary because of the existing `ParcelConverter` interface.  The problem with adding a way of configuring a class externally is matching the read and write parameters between the constructor, factory method, fields and methods.  This creates a huge mess and only duplicates what the `ParcelConverter` already does.

As always, I'm open to discussion, but I'm closing this issue and related PR for now.
